game.AddParticles("particles/combineball.pcf")
game.AddParticles("particles/vortigaunt_fx.pcf")
game.AddParticles("particles/cryo_fx.pcf")
game.AddParticles("particles/medicgun_beam.pcf")
game.AddParticles("particles/tbolt_fx_reborn.pcf")

PrecacheParticleSystem("vortigaunt_beam")
PrecacheParticleSystem("vortigaunt_beam_charge")
PrecacheParticleSystem("vortigaunt_charge_token")
PrecacheParticleSystem("vortigaunt_beam_b")
PrecacheParticleSystem("cryo_explosion_large")
PrecacheParticleSystem("cryo_explo_frags")
PrecacheParticleSystem("ice_impact")
PrecacheParticleSystem("ice_xfire_explode")
PrecacheParticleSystem("ice_tracer_smoke")
PrecacheParticleSystem("combineball")
PrecacheParticleSystem("eml_generic_shock_ligtning")
PrecacheParticleSystem("tbolt_core")
PrecacheParticleSystem("eml_generic_shock")
PrecacheParticleSystem("ice_smoke")
PrecacheParticleSystem("ice_freezing_halo")
PrecacheParticleSystem("snowcore_small") -- Charged Void Spear
PrecacheParticleSystem("ice_impact") -- Void Spear Impact (Small)
PrecacheParticleSystem("ice_impact_heavy") -- Void Spear Impact (Large)
PrecacheParticleSystem("jotunn_muzzle")