game.AddParticles("particles/combineball.pcf")
game.AddParticles("particles/vortigaunt_fx.pcf")
game.AddParticles("particles/horde_cryo_fx.pcf")
game.AddParticles("particles/horde_solar_fx.pcf")
game.AddParticles("particles/horde_spell_fx.pcf")
game.AddParticles("particles/medicgun_beam.pcf")
game.AddParticles("particles/storm_fx.pcf")
game.AddParticles("particles/horde_astral_fx.pcf")
game.AddParticles("particles/xen_destroyer_unit.pcf")
game.AddParticles("particles/xen_host_unit.pcf")
game.AddParticles("particles/horde_mutation.pcf")

PrecacheParticleSystem("xen_destroyer_flame")
PrecacheParticleSystem("xen_host_spit")
PrecacheParticleSystem("xen_host_spit_spawn")
PrecacheParticleSystem("xen_host_spit_impact")
PrecacheParticleSystem("horde_mutation_nemesis")

PrecacheParticleSystem("vortigaunt_beam")
PrecacheParticleSystem("vortigaunt_beam_charge")
PrecacheParticleSystem("vortigaunt_charge_token")
PrecacheParticleSystem("vortigaunt_beam_b")
PrecacheParticleSystem("cryo_explosion_large")
PrecacheParticleSystem("cryo_explo_frags")
PrecacheParticleSystem("ice_muzzle")
PrecacheParticleSystem("ice_xfire_explode")
PrecacheParticleSystem("ice_tracer_smoke")
PrecacheParticleSystem("combineball")
PrecacheParticleSystem("eml_generic_shock_ligtning")
PrecacheParticleSystem("tbolt_core")
PrecacheParticleSystem("eml_generic_shock")
PrecacheParticleSystem("ice_smoke")
PrecacheParticleSystem("ice_freezing_halo")
PrecacheParticleSystem("snowcore_small") -- Charged Void Spear
PrecacheParticleSystem("ice_impact") -- Void Spear Impact (Small)
PrecacheParticleSystem("ice_impact_heavy") -- Void Spear Impact (Large)
PrecacheParticleSystem("ice_arrow_hit")
PrecacheParticleSystem("ice_arrow_trail_3")
PrecacheParticleSystem("solar_orb")
PrecacheParticleSystem("solar_orb_charged_1")
PrecacheParticleSystem("solar_orb_charged_2")
PrecacheParticleSystem("solar_orb_explode")
PrecacheParticleSystem("solar_orb_charged_1_explode")
PrecacheParticleSystem("solar_orb_charged_2_explode")
PrecacheParticleSystem("solar_orb_warmth")
PrecacheParticleSystem("dark_orb")
PrecacheParticleSystem("dark_orb_charged_1")
PrecacheParticleSystem("dark_orb_charged_2")
PrecacheParticleSystem("dark_orb_explode")
PrecacheParticleSystem("dark_orb_explode_charged")
PrecacheParticleSystem("dark_orb_explode_charged_2")
PrecacheParticleSystem("floating_chaos")
PrecacheParticleSystem("solar_storm_hit")
PrecacheParticleSystem("solar_storm")
PrecacheParticleSystem("solar_storm_charged")
PrecacheParticleSystem("draconic_storm")
PrecacheParticleSystem("draconic_storm_hit")

PrecacheParticleSystem("nether_star")
PrecacheParticleSystem("pulsar_scourge")
PrecacheParticleSystem("nether_star_charged")
PrecacheParticleSystem("nether_star_explode")
PrecacheParticleSystem("scorcher_flame")
PrecacheParticleSystem("nether_mine_explode")
PrecacheParticleSystem("neutron_beam")
PrecacheParticleSystem("black_hole")
PrecacheParticleSystem("supernova")
PrecacheParticleSystem("supernova_explosion")